#在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
spring:
  application:
    name: spring-cloud-eurekaServer
server:
  port: 80
eureka:
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/